django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Connect path to portfolio_app urls
    path('', include('task_manager_app.urls')),
]

task_manager_app/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),

    # TASKS
    path('tasks/', views.TaskListView.as_view(), name = 'task-list'),
    path('tasks/<int:pk>/', views.TaskDetailView.as_view(), name = 'task-detail'),
    path('tasks/<int:pk>/update_task/', views.TaskUpdateView.as_view(), name = 'task-update'),
    path('tasks/<int:pk>/delete_task/', views.TaskDeleteView.as_view(), name = 'task-delete'),
    path('tasks/create_task<int:team_member_id>', views.TaskCreateView.as_view(), name = 'task-create'),

    # SET UP ROLE WITHIN TEAM
    path('create_team/', views.createTeamPage, name = 'create-team-page'),
    path('join_team/', views.joinTeamPage, name = 'join-team-page'),

    # TEAM LEAD PAGES
    path('team_lead/', views.teamLeadPage, name = 'team-lead-page'),
    path('team_lead/<int:team_member_id>/', views.getTeamMemberTasks, name = 'team-member-tasks'),
    path('team_lead/<int:team_member_id>/create_task/', views.createTask, name = 'task-create-page'),

    # TEAM MEMBER PAGES
    path('team_member', views.teamMemberPage, name = 'team-member-page'),
    path('team_member/<int:task_id>/', views.getTaskInfo, name = 'team-member-task-info'),
   
    # USER ACCOUNTS AND AUTHENTICATION PAGES
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.registerPage, name = 'register-page'),
]

task_manager_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

''' Team Lead Model '''
class TeamLead(models.Model):
    name = models.CharField(max_length=200)

    # Relational 
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

''' Team Model '''
class Team(models.Model):
    name = models.CharField(max_length=200)
    
    # Relational 
    lead = models.OneToOneField(TeamLead, on_delete=models.SET_NULL, null=True, related_name='teams')

    def __str__(self):
        return self.name

''' Team Member Model '''
class TeamMember(models.Model):
    name = models.CharField(max_length=200)
    
    # Relational 
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='members')
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
''' Task Model '''
class Task(models.Model):
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField(max_length=200, blank=False)
    due_date = models.DateField(blank=False)
    completion_stage = models.CharField(max_length=200, choices=[('Not Started', 'Not Started'),
                                                                 ('Working On', 'Working On'),
                                                                 ('Completed', 'Completed')], blank=False)
    email_sent = models.BooleanField(blank=True, default=False)
    ''' 
        One-to-Many Relationship 
        Each Task has a ForeignKey relationship with TeamMember 
        to represent the team member assigned to that task
    '''
    assignee = models.ForeignKey(TeamMember, on_delete=models.SET_NULL, null=True, related_name='tasks')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('task-detail', args=[str(self.id)]) 

task_manager_app/forms.py
from django import forms
from .models import *
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

# What is a form forms?
""" 
    The form class specifies the fields in the form, their layout, display wdigets,
    labels, initial values, valid values, and (once validated) the error messages 
    associated with invalid fields. The class also provides methods for rendering 
    itself in templates using predefined formated (tables, lists, etc.) or for 
    getting the value of any element (enabling fine-grained manual rendering)
"""

# What are they used for?
#   - Forms are used for taking input from the user in some manner
#     and using that informating for logical operations on databases.

# How do they work with HTML?
#   - Django maps fields defined in Django forms into HTML input fields.
#   - Django handles three distinct parts of the work involved in forms:
#       1. Preparing and restructuing data to make it ready for rendering
#       2. Creating HTML forms for the data
#       3. Receiving and processing submitted forms and data from the client

# Creates a team 
class CreateTeamForm(forms.Form):
    
    team_name = forms.CharField(max_length=100, required=True)

# Adds someone to team
class JoinTeamForm(forms.Form):
    
    team_name = forms.CharField(max_length=100, required=True)

###################################################################################################
#                                             TASKS                                               #
###################################################################################################

class TaskForm(ModelForm):
    due_date = forms.DateField(input_formats=['%Y-%m-%d'], widget=forms.DateInput(attrs={'type': 'date'}), required=True)

    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'completion_stage', 'assignee']
        template_name = 'task_update.html'

# This form allows a team member to change a tasks status
# This form is connected with:
#   1. getTaskInfo view
#   1. team_member_page.html
class ChangeCompletionStatusForm(ModelForm):
    class Meta:
        model = Task
        fields = ['completion_stage']

###################################################################################################
#                                       USER AUTHENTICATION                                       #
###################################################################################################

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

task_manager_app/views.py
from .models import *
from .forms import *
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import Group

###########################################################
#                    CLASS BASED MODELS                   #
###########################################################

''' Queries database to gather all tasks '''
class TaskListView(generic.ListView):
    model = Task

''' Queries database to gather task details '''
class TaskDetailView(generic.DetailView):
    model = Task

''' Queries database to gather task details to update '''
class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = ['title', 'description', 'due_date', 'completion_stage', 'assignee']
    template_name = 'task_manager_app/task_update.html'
    success_url = reverse_lazy('task-list') # This works but the others do not

''' Queries database to delete view '''
class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = ['title', 'description', 'due_date', 'completion_stage', 'assignee']
    template_name = 'task_manager_app/task_delete.html'
    success_url = reverse_lazy('team-member-page')

''' Creates new view '''
class TaskCreateView(generic.CreateView):
    model = Task
    ''' Use form_class instead of fields to insure that due_date has a proper widget '''
    form_class = TaskForm
    template_name = 'task_manager_app/task_create.html'
    success_url = reverse_lazy('team-member-tasks')

###########################################################
#                   FUNCTION BASED MODELS                 #
###########################################################


''' HOME PAGE VIEW '''
# Simple view that redirect back to the home page
def index(request):
    return render(request, 'task_manager_app/index.html')

#################################
#     TASK ORIENTED METHODS     #
#################################

""" View Function Used In: team_lead_page.html"""
# Allows a user to create a task
def createTask(request, team_member_id):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid:
            project = form.save()
            project.save()

            id = team_member_id
            return redirect(getTeamMemberTasks, team_member_id=id)
        
    # Filters team members to specific team
    team_member = TeamMember.objects.get(id=team_member_id)
    team_members = TeamMember.objects.filter(team_id=team_member.team_id)

    # Adjusting the queryset for the assignee field in the form
    form.fields['assignee'].queryset = team_members

    context = {'form': form}
    return render(request, 'task_manager_app/task_create.html', context)

#################################
#     TEAM ORIENTED METHODS     #
#################################

# Creates a team and sets user as team lead for team created
def createTeamPage(request):

    form = CreateTeamForm()

    if request.method == 'POST':
        form = CreateTeamForm(request.POST)
        if form.is_valid:
            team_name = form['team_name'].value()
            team_exists = Team.objects.filter(name=team_name).exists()
            
            if not team_exists:
                user = request.user
                user_name = request.user.username
                group = Group.objects.get(name='Team Lead')
                user.groups.add(group)

                # Create TeamLead object
                team_lead = TeamLead.objects.create(name=user_name, user=user)
                team_lead.save()

                # Create Team object
                team = Team.objects.create(name=team_name, lead=team_lead)
                team.save()

                messages.success(request, 'Successfully create team: ' + team_name)
                # Redirect to team page
                return redirect('index')
            else:
                error_message = "The team '{}' already exists. Please choose a different name.".format(team_name)
                return render(request, 'task_manager_app/create_team.html', {'form': form, 'error_message': error_message})

            
    context = {'form':form}
    return render(request, 'task_manager_app/create_team.html', context)

# Register a user to a team and give them a role
def joinTeamPage(request):

    form = JoinTeamForm()

    if request.method == 'POST':
        form = JoinTeamForm(request.POST)
        if form.is_valid:
            team_name = form['team_name'].value()
            team_exists = Team.objects.filter(name=team_name).exists()

            if team_exists:
                user = request.user
                user_name = request.user.username
                group = Group.objects.get(name='Team Member')
                user.groups.add(group)
            
                teamObj = Team.objects.get(name=team_name)
                team_member = TeamMember.objects.create(name=user_name, team=teamObj, user=user)
                team_member.save()

                messages.success(request, 'Successfully added to: ' + team_name)
                # Redirect to team page
                return redirect('index')
            else:
                error_message = "The team '{}' does not exist. Please try again.".format(team_name)
                return render(request, 'task_manager_app/join_team.html', {'form': form, 'error_message': error_message})

    context = {'form':form}
    return render(request, 'task_manager_app/join_team.html', context)

""" View Function Used In: base_template.html"""
# Queries needed data from database for the currect user(team lead) trying to access team page
def teamLeadPage(request):
    # Grab team ID
    user_id = request.user.id
    team_lead = TeamLead.objects.filter(user_id=user_id).get()
    team = Team.objects.filter(lead_id=team_lead.id).get()

    # Grab all team member objects for specified team
    team_members = TeamMember.objects.filter(team_id=team.id)

    context = {
        'team': team,
        'team_members': team_members,
    }
    return render(request, 'task_manager_app/team_lead_page.html', context)

""" View Function Used In: team_lead_page.html"""
# Grabs tasks related to team member selected
def getTeamMemberTasks(request, team_member_id):
    # Grab team ID
    user_id = request.user.id
    team_lead = TeamLead.objects.filter(user_id=user_id).get()
    team = Team.objects.filter(lead_id=team_lead.id).get()

    # Grab all team member objects for specified team
    team_members = TeamMember.objects.filter(team_id=team.id)
    # Grab user(team member) clicked on
    member = TeamMember.objects.get(id=team_member_id)
    # Grab all tasks related to user(team member)
    tasks = Task.objects.filter(assignee_id=team_member_id)
    
    context = {'team' : team,
               'team_members' : team_members,
               'selected_member' : member,
               'selected_tasks' : tasks}
    return render(request, 'task_manager_app/team_lead_page.html', context)

""" View Function Used In: base_template.html"""
# Queries needed data from database for the currect user(team member) trying to access team page
def teamMemberPage(request):
    # Grab team member id
    user_id = request.user.id
    team_member = TeamMember.objects.get(user_id=user_id)

    # Grab all tasks related to user(team member)
    tasks = Task.objects.filter(assignee_id=team_member.id)

    context = {
        'tasks' : tasks,
    }

    return render(request, 'task_manager_app/team_member_page.html', context)

""" View Function Used In: team_member_page.html"""
# Grabs task data related to which task was selected
def getTaskInfo(request, task_id):
    # Grab team member id
    user_id = request.user.id
    team_member = TeamMember.objects.get(user_id=user_id)

    # Grab all tasks related to user(team member)
    tasks = Task.objects.filter(assignee_id=team_member.id)

    # Grab specific task information
    task = Task.objects.get(id=task_id)
    title = task.title
    description = task.description
    due_date = task.due_date
    completion_stage = task.completion_stage

    form = ChangeCompletionStatusForm()

    if request.method == 'POST':
        form = ChangeCompletionStatusForm(request.POST, instance=task)
        if form.is_valid():
            task.save()

            task_name = task.title
            messages.success(request, 'Successfully updated task: ' + task_name)
    else:
        form = ChangeCompletionStatusForm(instance=task)

    context = {
        'form' : form,
        'tasks' : tasks,
        'task' : task,
        'title' : title,
        'description' : description,
        'due_date' : due_date,
        'completion_stage' : completion_stage,
        'selected_task' : task,
        'selected_tasks' : tasks,
    }

    return render(request, 'task_manager_app/team_member_page.html', context)


#################################
#       USER AUTHENTICATION     #
#################################

""" View Function Used In: base_template.html"""
# Registers a user to the database
def registerPage(request):
    
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + username)
            return redirect('login')
    
    context = {'form':form}
    return render(request, 'registration/register.html', context)

task_manager_app/templates/task_manager_app/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Page</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f0f0f0;
    }

    .navbar {
      background-color: #333;
      overflow: hidden;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 20px;
    }
    .navbar-brand {
      color: #f2f2f2;
      text-decoration: none;
      font-family: "Crimson Text", serif;
      font-size: 30px
    }
    .navbar-links {
      display: flex;
      align-items: center;
    }
    .navbar-link {
        color: #f2f2f2;
        text-decoration: none;
        padding: 10px 20px;
        font-family: "Crimson Text", serif;
        font-size: 22px;
    }
    .navbar-link:hover {
      background-color: #ddd;
      color: black;
    }
    .navbar-username {
      color: #f2f2f2;
      text-decoration: none;
      padding: 10px 20px;
      font-family: "Crimson Text", serif;
      font-size: 22px;
    } 
    .navbar-link img {
      width: 40px; /* Adjust the width as needed */
      height: 40px; /* Adjust the height as needed */
      border-radius: 10%; /* Makes the image circular */
    }


    .container-left {
      max-width: 800px;
      margin-left: 0px;
      margin-bottom: 20px;
      border: 1px solid black;
      text-align: left;
      padding: 20px;
    }
    .container-middle {
        max-width: 800px;
        margin: 50px auto;
        text-align: center;
    }
    .container-right {
        max-width: 800px;
        margin: 50px auto;
        text-align: right;
    }

    .btn {
      display: inline-block;
      padding: 10px 20px;
      background-color: #007bff;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
      margin-right: 10px;
      transition: background-color 0.3s;
    }
    .button-layout {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-top: 20px;
    }
    .btn:hover {
      background-color: #0056b3;
    }

  </style>
</head>

<body>
    <div class="navbar">
        <a class="navbar-brand" href="{% url 'index' %}">Tasky</a>
        <div class="navbar-links">
            <a class="navbar-link" href="{% url 'index' %}">Home</a>

            <!-- Give option to (make or join a team) or (view users team view) -->
            {% if user.is_authenticated %}
              {% if user.groups.all.0.name == 'Team Lead'%}
                <a class="navbar-link" href="{% url 'team-lead-page' %}">Team</a>
              {% elif user.groups.all.0.name == 'Team Member' %}
                <a class="navbar-link" href="{% url 'team-member-page' %}">Team</a>
              {% else %}
                <a class="navbar-link" href="{% url 'create-team-page' %}">Create Team</a>
                <a class="navbar-link" href="{% url 'join-team-page' %}">Join Team</a>
              {% endif %}
            {% endif %}

            <!-- Show (login and register) or (username and logout) -->
            {% if user.is_authenticated %}
              <a class="navbar-link" href="{% url 'logout' %}">Logout</a>
              <a class="navbar-link" href="#">
                <img src="{% static 'images/profile.png' %}" alt="Profile Image">
              </a>
            {% else %}
              <a class="navbar-link" href="{% url 'login' %}">Login</a>
              <a class="navbar-link" href="{% url 'register-page' %}">Register</a>
            {% endif %}
        </div>
    </div>

    <div class="col-sm-10">
        <!-- add block content from html template -->
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

task_manager_app/templates/task_manager_app/create_team.html
{% extends 'task_manager_app/base_template.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
      body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        overflow: hiddin; /* Prevent scroll wheel */
      }


      .login-image {
        position: relative;
        height: 100vh; /* Full height of viewport */
        overflow: hidden; /* Hide any content that overflows the container */
      }
      .login-image img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover; /* Ensure the image covers the entire container */
      }


      .login-container {
        position: absolute;
        top: 30%; /* Adjust the position */
        left: 50%;
        transform: translate(-50%, -50%);
        background: rgba(255, 255, 255, 0.8); /* Semi-transparent white background */
        padding: 40px; /* Adjust padding */
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
        width: 80%; /* Adjust width */
        max-width: 400px; /* Adjust max width */
      }
      .login-heading {
          font-size: 24px;
          font-weight: bold;
          color: #333; /* Change color as needed */
          text-transform: uppercase;
          margin-bottom: 20px;
      }
      .login-container table tr {
        margin-bottom: 10px; /* Adjust the spacing between table rows */
      }
      .login-container .submit-button {
        margin-top: 20px; /* Adjust the margin-top for the submit button */
        width: 130px;
        height: 30px;
        font-size: 14px;
      }
    </style>
</head>

<body>
  <div class="login-image">
    <img src="{% static 'images/team_background2.jpg' %}">
    <div class="login-container">
      <h2 class="login-heading">Create a Team</h2>
        <form method="post">
            {% csrf_token %}
            <table style="margin: 0 auto; padding-right: 30px;">
              <tr>
                <td>{{ "Team Name" }}</td>
                <td>{{ form.team_name }}</td>
              </tr>
            </table>
            <button type"submit" class="submit-button" value="Login">Create Team</button>
        </form>
        {{ form.field.errors }}
    </div>
  </div>
</body>
 
{% endblock %}

task_manager_app/templates/task_manager_app/index.html
<!-- inherit from base.html-->
{% extends "task_manager_app/base_template.html" %}

<!-- Replace block content in base_template.html -->
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            height: calc(100vh - 86px); /* Adjusts container height (removes scroll bar) */
        }

        .pure-black-image {
            flex-basis: 75%; 
            max-width: 75%; 
            position: relative; 
            overflow: hidden; /* Hide any content that overflows the container */
            height: 100% /* Ensure container takes full height */
        }

        .task-manager-image {
            flex-basis: 25%; 
            max-width: 25%; 
            position: relative; 
            overflow: hidden; /* Hide any content that overflows the container */
            height: 100%; /* Ensure container takes full height */
        }

        img {
            display: block; /* Ensure images don't have any space below them */
            width: 100%; /* Make images responsive */
            height: 100%; /* Make images responsive */
            object-fit: cover;
            /*max-height: calc(100vh - 100px);*/
        }

        .header {
            position: absolute;
            top: 30%; 
            left: 50%; 
            transform: translateX(-50%); /* Center the text horizontally */
            color: white;
            font-size: 40px; 
            font-family: "Crimson Text", serif;
            text-align: center;
        }

        .paragraph {
            position: absolute; 
            top: 40%; 
            left: 50%; 
            transform: translate(-50%, -50%); /* Center the text horizontally and vertically */
            color: white; 
            font-size: 22px; 
            font-family: "Crimson Text", serif;
            text-align: center; 
            width: 80%; 
            height: auto; 
        }
    </style>
</head>

<body>
    <div class="container">

        <!-- Black Image -->
        <div class="pure-black-image">
            <img src="{% static 'images/pure_black.jpg' %}">
            <div class="header">
                Tasky Management
            </div>
            <div class="paragraph">
                Streamline Your Tasks, Simplify Your Workflow, Master Your Management.
            </div>
        </div>

        <!-- Colored Image -->
        <div class="task-manager-image">
            <img src="{% static 'images/project_planning.jpg' %}">
        </div>

    </div>
</body>
</html>

{% endblock %}

task_manager_app/templates/task_manager_app/join_team.html
{% extends 'task_manager_app/base_template.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
      body, html {
        margin: 0;
        padding: 0;
        height: 100%;
      }


      .login-image {
        position: relative;
        height: 100vh; /* Full height of viewport */
        overflow: hidden; /* Hide any content that overflows the container */
      }
      .login-image img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover; /* Ensure the image covers the entire container */
      }


      .login-container {
        position: absolute;
        top: 30%; /* Adjust the position */
        left: 50%;
        transform: translate(-50%, -50%);
        background: rgba(255, 255, 255, 0.8); /* Semi-transparent white background */
        padding: 40px; /* Adjust padding */
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
        width: 80%; /* Adjust width */
        max-width: 400px; /* Adjust max width */
      }
      .login-heading {
          font-size: 24px;
          font-weight: bold;
          color: #333; /* Change color as needed */
          text-transform: uppercase;
          margin-bottom: 20px;
      }
      .login-container table tr {
        margin-bottom: 10px; /* Adjust the spacing between table rows */
      }
      .login-container .submit-button {
        margin-top: 20px; /* Adjust the margin-top for the submit button */
        width: 130px;
        height: 30px;
        font-size: 14px;
      }
    </style>
</head>

<body>
  <div class="login-image">
    <img src="{% static 'images/team_background.jpg' %}">
    <div class="login-container">
      <h2 class="login-heading">Join a Team</h2>
        <form method="post">
            {% csrf_token %}
            <table style="margin: 0 auto; padding-right: 30px;">
              <tr>
                <td>{{ "Team Name" }}</td>
                <td>{{ form.team_name }}</td>
              </tr>
            </table>
            <button type"submit" class="submit-button" value="Login">Join Team</button>
        </form>
        {{ form.field.errors }}
    </div>
  </div>
</body>
 
{% endblock %}

task_manager_app/templates/task_manager_app/task_create.html
{% extends "task_manager_app/base_template.html" %}

{% block extra_head %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            console.log("Document ready.");
            var dueDateField = $("#id_due_date");
            console.log("Due date field:", dueDateField);
            if (dueDateField.length) {
                console.log("Initializing datepicker.");
                dueDateField.datepicker();
            } else {
                console.error("Due date field not found.");
            }
        });
    </script>


{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type"submit" value="Submit">Submit</button>
    </form>
{% endblock %}

task_manager_app/templates/task_manager_app/task_delete.html
{% extends "task_manager_app/base_template.html" %}

{% block content %}

    <style>

        .btn-layout {
            display: flex;
            align-items: center;
            gap: 10px;
        }

    </style>

    <p> Are you sure you want to remove task: "{{ task.title }}"?</p>

    <div class="btn-layout">

        <!-- Cancels deletion and reverts back to task-list -->
        <a href="{% url 'team-member-page' %}">
            <button class="btn">Cancel</button>
        </a>

        <!-- Deletes task from database -->
        <form method="post">
            {% csrf_token %}
            <button class="btn" type"submit" value="Confirm">Confirm</button>
        </form>

    </div>

{% endblock %}

task_manager_app/templates/task_manager_app/task_detail.html
<!-- inherit from base.html-->
{% extends "task_manager_app/base_template.html" %}

<!-- Replace block content in base_template.html -->
{% block content %}

<!-- Displays basic information in regards to the student -->
<h1>Task: {{ task.title }}</h1>
<div class="container-left">
    <p><strong>Description: </strong> {{ task.description }}</p>
    <p><strong>Due Date: </strong> {{ task.due_date }}</p>
    <p><strong>Completion Stage: </strong> {{ task.completion_stage }}</p>
    <p><strong>Assignee: </strong> {{ task.assignee }}</p>

    <!-- Directs us to the Task List View-->
    <a class="nav-link" aria-current="page" href="{% url 'task-list' %}">
        <button class="btn">Task List</button>
    </a>
</div>
    
{% endblock %}

task_manager_app/templates/task_manager_app/task_update.html
{% extends "task_manager_app/base_template.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type"submit" value="Confirm">Update</button>
    </form>
{% endblock %}